[build]
builder = "NIXPACKS"

[deploy]
startCommand = "gunicorn app:server --bind 0.0.0.0:$PORT"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[environments.production.variables]
PYTHON_VERSION = "3.9"
BPS_API_KEY = "0c170847a66a0641ee3d16a3c292d6a9"